CREATE TYPE "public"."school_year" AS ENUM('Freshman', 'Sophomore', 'Junior', 'Senior', 'Graduate');--> statement-breakpoint
CREATE TYPE "public"."stripe_account_status" AS ENUM('pending', 'active', 'restricted', 'inactive');--> statement-breakpoint
CREATE TABLE "discuno_account" (
	"user_id" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"provider_account_id" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "discuno_account_provider_provider_account_id_pk" PRIMARY KEY("provider","provider_account_id")
);
--> statement-breakpoint
CREATE TABLE "discuno_calcom_token" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discuno_calcom_token_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"calcom_user_id" integer NOT NULL,
	"calcom_username" varchar(255) NOT NULL,
	"access_token" text NOT NULL,
	"refresh_token" text NOT NULL,
	"access_token_expires_at" timestamp with time zone NOT NULL,
	"refresh_token_expires_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "discuno_calcom_token_userId_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "discuno_major" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discuno_major_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255),
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "discuno_major_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "discuno_mentor_event_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discuno_mentor_event_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"calcom_event_type_id" integer NOT NULL,
	"calcom_event_type_slug" varchar(255) NOT NULL,
	"is_enabled" boolean DEFAULT false NOT NULL,
	"custom_price" integer,
	"currency" varchar(3) DEFAULT 'USD' NOT NULL,
	"requires_payment" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "mentor_event_types_user_event_type_unique" UNIQUE("user_id","calcom_event_type_id")
);
--> statement-breakpoint
CREATE TABLE "discuno_mentor_review" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discuno_mentor_review_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"mentor_id" varchar(255) NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"rating" integer NOT NULL,
	"review" varchar(1000),
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "rating_check" CHECK ("discuno_mentor_review"."rating" >= 1 AND "discuno_mentor_review"."rating" <= 5)
);
--> statement-breakpoint
CREATE TABLE "discuno_mentor_stripe_account" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discuno_mentor_stripe_account_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"stripe_account_id" varchar(255) NOT NULL,
	"stripe_account_status" "stripe_account_status",
	"onboarding_completed" timestamp with time zone,
	"payouts_enabled" boolean DEFAULT false NOT NULL,
	"charges_enabled" boolean DEFAULT false NOT NULL,
	"details_submitted" boolean DEFAULT false NOT NULL,
	"requirements" jsonb DEFAULT '{}',
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "discuno_mentor_stripe_account_userId_unique" UNIQUE("user_id"),
	CONSTRAINT "discuno_mentor_stripe_account_stripeAccountId_unique" UNIQUE("stripe_account_id")
);
--> statement-breakpoint
CREATE TABLE "discuno_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discuno_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"description" text,
	"created_by_id" varchar(255) NOT NULL,
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "discuno_post_createdById_unique" UNIQUE("created_by_id")
);
--> statement-breakpoint
CREATE TABLE "discuno_school" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discuno_school_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255),
	"domain" varchar(255),
	"location" varchar(255),
	"image" varchar(255),
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "discuno_school_name_unique" UNIQUE("name"),
	CONSTRAINT "discuno_school_domain_unique" UNIQUE("domain")
);
--> statement-breakpoint
CREATE TABLE "discuno_session" (
	"session_token" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "discuno_user_major" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discuno_user_major_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"major_id" integer NOT NULL,
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "discuno_user_profile" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discuno_user_profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"bio" varchar(1000),
	"school_year" "school_year" NOT NULL,
	"graduation_year" integer NOT NULL,
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "discuno_user_profile_userId_unique" UNIQUE("user_id"),
	CONSTRAINT "grad_year_check" CHECK ("discuno_user_profile"."graduation_year" >= EXTRACT(YEAR FROM CURRENT_DATE))
);
--> statement-breakpoint
CREATE TABLE "discuno_user_school" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discuno_user_school_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"school_id" integer NOT NULL,
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "discuno_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255),
	"email_verified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255),
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "discuno_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "discuno_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "discuno_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
CREATE TABLE "discuno_waitlist" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discuno_waitlist_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(255) NOT NULL,
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "discuno_account" ADD CONSTRAINT "discuno_account_user_id_discuno_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."discuno_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discuno_calcom_token" ADD CONSTRAINT "discuno_calcom_token_user_id_discuno_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."discuno_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discuno_mentor_event_type" ADD CONSTRAINT "discuno_mentor_event_type_user_id_discuno_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."discuno_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discuno_mentor_review" ADD CONSTRAINT "discuno_mentor_review_mentor_id_discuno_user_id_fk" FOREIGN KEY ("mentor_id") REFERENCES "public"."discuno_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discuno_mentor_review" ADD CONSTRAINT "discuno_mentor_review_user_id_discuno_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."discuno_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discuno_mentor_stripe_account" ADD CONSTRAINT "discuno_mentor_stripe_account_user_id_discuno_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."discuno_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discuno_post" ADD CONSTRAINT "discuno_post_created_by_id_discuno_user_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."discuno_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discuno_session" ADD CONSTRAINT "discuno_session_user_id_discuno_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."discuno_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discuno_user_major" ADD CONSTRAINT "discuno_user_major_user_id_discuno_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."discuno_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discuno_user_major" ADD CONSTRAINT "discuno_user_major_major_id_discuno_major_id_fk" FOREIGN KEY ("major_id") REFERENCES "public"."discuno_major"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discuno_user_profile" ADD CONSTRAINT "discuno_user_profile_user_id_discuno_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."discuno_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discuno_user_school" ADD CONSTRAINT "discuno_user_school_user_id_discuno_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."discuno_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discuno_user_school" ADD CONSTRAINT "discuno_user_school_school_id_discuno_school_id_fk" FOREIGN KEY ("school_id") REFERENCES "public"."discuno_school"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "discuno_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "calcom_tokens_user_id_idx" ON "discuno_calcom_token" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "calcom_tokens_access_token_idx" ON "discuno_calcom_token" USING btree ("access_token");--> statement-breakpoint
CREATE INDEX "calcom_tokens_username_idx" ON "discuno_calcom_token" USING btree ("calcom_username");--> statement-breakpoint
CREATE INDEX "mentor_event_types_user_event_type_idx" ON "discuno_mentor_event_type" USING btree ("user_id","calcom_event_type_id");--> statement-breakpoint
CREATE INDEX "mentor_event_types_user_id_idx" ON "discuno_mentor_event_type" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "mentor_event_types_calcom_event_type_id_idx" ON "discuno_mentor_event_type" USING btree ("calcom_event_type_id");--> statement-breakpoint
CREATE INDEX "mentor_stripe_accounts_user_id_idx" ON "discuno_mentor_stripe_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "mentor_stripe_accounts_stripe_account_id_idx" ON "discuno_mentor_stripe_account" USING btree ("stripe_account_id");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "discuno_post" USING btree ("created_by_id");--> statement-breakpoint
CREATE INDEX "name_idx" ON "discuno_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "created_at_created_by_idx" ON "discuno_post" USING btree ("created_at","created_by_id");--> statement-breakpoint
CREATE INDEX "posts_created_at_partial_idx" ON "discuno_post" USING btree ("created_at") WHERE deleted_at IS NULL;--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "discuno_session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "major_user_compound_idx" ON "discuno_user_major" USING btree ("major_id","user_id");--> statement-breakpoint
CREATE INDEX "graduation_school_year_idx" ON "discuno_user_profile" USING btree ("graduation_year","school_year");--> statement-breakpoint
CREATE INDEX "user_profiles_compound_idx" ON "discuno_user_profile" USING btree ("user_id","graduation_year","school_year");--> statement-breakpoint
CREATE INDEX "user_profiles_grad_year_partial_idx" ON "discuno_user_profile" USING btree ("graduation_year") WHERE deleted_at IS NULL;--> statement-breakpoint
CREATE INDEX "user_school_idx" ON "discuno_user_school" USING btree ("user_id","school_id");--> statement-breakpoint
CREATE INDEX "school_user_compound_idx" ON "discuno_user_school" USING btree ("school_id","user_id");