CREATE TYPE "public"."booking_status" AS ENUM('ACCEPTED', 'PENDING', 'CANCELLED', 'REJECTED');--> statement-breakpoint
CREATE TABLE "discuno_booking" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discuno_booking_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"calcom_booking_id" integer NOT NULL,
	"calcom_uid" varchar(255) NOT NULL,
	"title" varchar(500) NOT NULL,
	"start_time" timestamp with time zone NOT NULL,
	"end_time" timestamp with time zone NOT NULL,
	"status" "booking_status" DEFAULT 'PENDING' NOT NULL,
	"organizer_id" varchar(255) NOT NULL,
	"organizer_name" varchar(255) NOT NULL,
	"organizer_email" varchar(255) NOT NULL,
	"organizer_username" varchar(255) NOT NULL,
	"attendee_name" varchar(255) NOT NULL,
	"attendee_email" varchar(255) NOT NULL,
	"attendee_time_zone" varchar(100),
	"price" integer,
	"currency" varchar(3) DEFAULT 'USD',
	"mentor_event_type_id" integer,
	"responses" jsonb DEFAULT '{}',
	"webhook_payload" jsonb NOT NULL,
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "discuno_booking_calcomBookingId_unique" UNIQUE("calcom_booking_id"),
	CONSTRAINT "discuno_booking_calcomUid_unique" UNIQUE("calcom_uid")
);
--> statement-breakpoint
CREATE TABLE "discuno_event_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discuno_event_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"calcom_event_type_id" integer NOT NULL,
	"calcom_event_type_slug" varchar(255) NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text,
	"duration" integer NOT NULL,
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "discuno_event_type_calcomEventTypeId_unique" UNIQUE("calcom_event_type_id"),
	CONSTRAINT "discuno_event_type_calcomEventTypeSlug_unique" UNIQUE("calcom_event_type_slug")
);
--> statement-breakpoint
ALTER TABLE "discuno_mentor_event_type" DROP CONSTRAINT "mentor_event_types_user_event_type_unique";--> statement-breakpoint
DROP INDEX "mentor_event_types_calcom_event_type_id_idx";--> statement-breakpoint
DROP INDEX "mentor_event_types_user_event_type_idx";--> statement-breakpoint
ALTER TABLE "discuno_mentor_event_type" ADD COLUMN "event_type_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "discuno_user_profile" ADD COLUMN "timezone" varchar(255) DEFAULT 'UTC' NOT NULL;--> statement-breakpoint
ALTER TABLE "discuno_booking" ADD CONSTRAINT "discuno_booking_organizer_id_discuno_user_id_fk" FOREIGN KEY ("organizer_id") REFERENCES "public"."discuno_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discuno_booking" ADD CONSTRAINT "discuno_booking_mentor_event_type_id_discuno_mentor_event_type_id_fk" FOREIGN KEY ("mentor_event_type_id") REFERENCES "public"."discuno_mentor_event_type"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "bookings_calcom_booking_id_idx" ON "discuno_booking" USING btree ("calcom_booking_id");--> statement-breakpoint
CREATE INDEX "bookings_calcom_uid_idx" ON "discuno_booking" USING btree ("calcom_uid");--> statement-breakpoint
CREATE INDEX "bookings_organizer_id_idx" ON "discuno_booking" USING btree ("organizer_id");--> statement-breakpoint
CREATE INDEX "bookings_start_time_idx" ON "discuno_booking" USING btree ("start_time");--> statement-breakpoint
CREATE INDEX "bookings_status_idx" ON "discuno_booking" USING btree ("status");--> statement-breakpoint
CREATE INDEX "bookings_mentor_event_type_id_idx" ON "discuno_booking" USING btree ("mentor_event_type_id");--> statement-breakpoint
CREATE INDEX "event_types_calcom_event_type_id_idx" ON "discuno_event_type" USING btree ("calcom_event_type_id");--> statement-breakpoint
CREATE INDEX "event_types_slug_idx" ON "discuno_event_type" USING btree ("calcom_event_type_slug");--> statement-breakpoint
ALTER TABLE "discuno_mentor_event_type" ADD CONSTRAINT "discuno_mentor_event_type_event_type_id_discuno_event_type_id_fk" FOREIGN KEY ("event_type_id") REFERENCES "public"."discuno_event_type"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "mentor_event_types_event_type_id_idx" ON "discuno_mentor_event_type" USING btree ("event_type_id");--> statement-breakpoint
CREATE INDEX "mentor_event_types_user_event_type_idx" ON "discuno_mentor_event_type" USING btree ("user_id","event_type_id");--> statement-breakpoint
ALTER TABLE "discuno_mentor_event_type" DROP COLUMN "calcom_event_type_id";--> statement-breakpoint
ALTER TABLE "discuno_mentor_event_type" DROP COLUMN "calcom_event_type_slug";--> statement-breakpoint
ALTER TABLE "discuno_mentor_event_type" DROP COLUMN "requires_payment";--> statement-breakpoint
ALTER TABLE "discuno_mentor_event_type" ADD CONSTRAINT "mentor_event_types_user_event_type_unique" UNIQUE("user_id","event_type_id");