CREATE TYPE "public"."payment_status" AS ENUM('succeeded', 'pending', 'failed');--> statement-breakpoint
ALTER TYPE "public"."booking_status" ADD VALUE 'AWAITING_PAYMENT' BEFORE 'ACCEPTED';--> statement-breakpoint
CREATE TABLE "discuno_payment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discuno_payment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"booking_id" integer NOT NULL,
	"stripe_payment_intent_id" varchar(255) NOT NULL,
	"amount" integer NOT NULL,
	"currency" varchar(3) NOT NULL,
	"status" "payment_status" NOT NULL,
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "discuno_payment_stripePaymentIntentId_unique" UNIQUE("stripe_payment_intent_id")
);
--> statement-breakpoint
ALTER TABLE "discuno_payment" ADD CONSTRAINT "discuno_payment_booking_id_discuno_booking_id_fk" FOREIGN KEY ("booking_id") REFERENCES "public"."discuno_booking"("id") ON DELETE no action ON UPDATE no action;