CREATE TABLE "discuno_mentor_event_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discuno_mentor_event_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"calcom_event_type_id" integer NOT NULL,
	"calcom_event_type_slug" varchar(255) NOT NULL,
	"is_enabled" boolean DEFAULT false NOT NULL,
	"custom_price" integer,
	"currency" varchar(3) DEFAULT 'USD' NOT NULL,
	"requires_payment" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "mentor_event_types_user_event_type_unique" UNIQUE("user_id","calcom_event_type_id")
);
--> statement-breakpoint
CREATE TABLE "discuno_mentor_stripe_account" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discuno_mentor_stripe_account_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"stripe_account_id" varchar(255) NOT NULL,
	"stripe_account_status" varchar(50) DEFAULT 'pending' NOT NULL,
	"onboarding_completed" timestamp with time zone,
	"payouts_enabled" boolean DEFAULT false NOT NULL,
	"charges_enabled" boolean DEFAULT false NOT NULL,
	"details_submitted" boolean DEFAULT false NOT NULL,
	"requirements" jsonb DEFAULT '{}',
	"disabled_reason" varchar(255),
	"updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "discuno_mentor_stripe_account_user_id_unique" UNIQUE("user_id"),
	CONSTRAINT "discuno_mentor_stripe_account_stripe_account_id_unique" UNIQUE("stripe_account_id")
);
--> statement-breakpoint
ALTER TABLE "discuno_school" ADD COLUMN "domain" varchar(255);--> statement-breakpoint
ALTER TABLE "discuno_mentor_event_type" ADD CONSTRAINT "discuno_mentor_event_type_user_id_discuno_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."discuno_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discuno_mentor_stripe_account" ADD CONSTRAINT "discuno_mentor_stripe_account_user_id_discuno_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."discuno_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "mentor_event_types_user_event_type_idx" ON "discuno_mentor_event_type" USING btree ("user_id","calcom_event_type_id");--> statement-breakpoint
CREATE INDEX "mentor_event_types_user_id_idx" ON "discuno_mentor_event_type" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "mentor_event_types_calcom_event_type_id_idx" ON "discuno_mentor_event_type" USING btree ("calcom_event_type_id");--> statement-breakpoint
CREATE INDEX "mentor_stripe_accounts_user_id_idx" ON "discuno_mentor_stripe_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "mentor_stripe_accounts_stripe_account_id_idx" ON "discuno_mentor_stripe_account" USING btree ("stripe_account_id");--> statement-breakpoint
ALTER TABLE "discuno_school" ADD CONSTRAINT "discuno_school_domain_unique" UNIQUE("domain");